urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import patterns

urlpatterns = patterns('',
    (r'item/(?P<id_item>\d+)', 'apps.lock.views.show_item'),
    (r'print_receipt/(?P<id_item>\d+)', 'apps.lock.views.print_receipt'),    
    (r'', 'apps.lock.views.index')
)

models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.translation import ugettext as _

class AbstractName(models.Model):
    class Meta:
        abstract = True
        verbose_name = 'Nazwa'
        verbose_name_plural = 'Nazwy'

    name = models.CharField(max_length = 256,
                            verbose_name = 'Nazwa')

    def __unicode__(self):
        return self.name

class RoomType(AbstractName):
    class Meta:
        db_table = 'lock_room_type'
        verbose_name = 'Typ pokoju'
        verbose_name_plural = 'Typy pokojów'

class Room(AbstractName):
    class Meta:
        db_table = 'lock_room'
        verbose_name = 'Pokój'
        verbose_name_plural = 'Pokoje'

    type = models.ForeignKey('RoomType',
                             verbose_name = 'Typ')
    department = models.ForeignKey('trainman.Department',
                                   verbose_name = 'Wydział')

    def __unicode__(self):
        return '%s: %s' % (unicode(self.department), self.name)

class ItemType(AbstractName):
    class Meta:
        db_table = 'lock_item_type'
        verbose_name = 'Typ przedmiotu'
        verbose_name_plural = 'Typy przedmiotów'

    keys = models.ManyToManyField('Key',
                                  null = True,
                                  blank = True,
                                  verbose_name = 'Klucz')

class Item(AbstractName):
    class Meta:
        db_table = 'lock_item'
        verbose_name = 'Przedmiot'
        verbose_name_plural = 'przedmioty'
        ordering = ('name', )

    serial_number = models.CharField(max_length = 64,
                            verbose_name = 'Numer seryjny')
    inventory_number = models.CharField(max_length = 64,
                                        verbose_name = 'Numer inwentarzowy')
    invoice_number = models.CharField(max_length = 64,
                                        verbose_name = 'Numer faktury')
    price = models.FloatField(verbose_name = 'Cena (PLN):')
    image = models.ImageField(upload_to = 'lock/img/',
                              null = True,
                              blank = True,
                              verbose_name = 'Zdjęcie przedmiotu')
    type = models.ForeignKey('ItemType',
                             verbose_name = 'Typ')
    room = models.ForeignKey('Room',
                             verbose_name = 'Pokój')
    item = models.ForeignKey('Item',
                             related_name = 'related_items',
                             null = True,
                             blank = True,
                             verbose_name = 'Przedmiot')
    users = models.ManyToManyField('trainman.UserProfile',
                                  through = 'ItemUser',
                                  null = True,
                                  blank = True,
                                  verbose_name = 'Użytkownicy')
    properties = models.ManyToManyField('Key',
                                        through = 'Property',
                                        null = True,
                                        blank = True,
                                        verbose_name = 'Właściwości')
    is_verified = models.BooleanField(default = False,
                                    verbose_name = _(u'Zweryfikowany'))

    def __unicode__(self):
        return '%s, %s (%s)' % (unicode(self.type), self.name, self.serial_number)
    
    def get_item_owner(self):
        try:
            return self.users.filter(itemuser__type = ITEM_USER_TYPE_OWNER)[0]
        except:
            return ''
    
    def get_item_user(self):
        try:
            return self.users.filter(itemuser__type = ITEM_USER_TYPE_USER)[0]
        except:
            return ''

ITEM_USER_TYPE_OWNER = 1
ITEM_USER_TYPE_USER = 2

class ItemUserType(AbstractName):
    class Meta:
        db_table = 'lock_item_user_type'
        verbose_name = 'Typ własności'
        verbose_name_plural = 'Typy własności'
        
    def __unicode__(self):
        return '%s' % (self.name)

class ItemUser(models.Model):
    class Meta:
        db_table = 'lock_item__to__user'
        verbose_name = 'Użytkownik'
        verbose_name_plural = 'Użytkownicy'

    item = models.ForeignKey('Item',
                             verbose_name = 'Przedmiot')
    user = models.ForeignKey('trainman.UserProfile',
                             verbose_name = 'Użytkownik')
    type = models.ForeignKey('ItemUserType',
                             verbose_name = 'Typ')
    date = models.DateField()

    def __unicode__(self):
        return '%s - %s, %s' % (unicode(self.item), unicode(self.user), unicode(self.type))

class Key(AbstractName):
    class Meta:
        db_table = 'lock_key'
        verbose_name = 'Właściwość'
        verbose_name_plural = 'Właściwości'

class Property(models.Model):
    class Meta:
        db_table = 'lock_property'
        verbose_name = 'Właściwość przedmiotu'
        verbose_name_plural = 'Właściwości przedmiotów' 

    value = models.CharField(max_length = 1024,
                             verbose_name = 'Wartość')
    key = models.ForeignKey('Key',
                            verbose_name = 'Właściwość')
    item = models.ForeignKey('Item',
                             verbose_name = 'Przedmiot')

    def __unicode__(self):
        return '%s, (%s: %s)' % (unicode(self.item), unicode(self.key), self.value)

class LockAdmin(models.Model):
    class Meta:
        db_table = 'lock_admin'
        verbose_name = 'Administrator Locka'
        verbose_name_plural = 'Administratorzy Locka'

    user_profile = models.OneToOneField('trainman.UserProfile',
                                        verbose_name = 'Użytkownik')
    departments = models.ManyToManyField('trainman.Department',
                                         null = True,
                                         blank = True,
                                         verbose_name = 'Administrowane jednostki')

    def __unicode__(self):
        return unicode(self.user_profile)

templates/lock/base.html
{% extends "column_1.html" %}

{% load i18n pagination %}

{% block page_title %} {% trans "Inwentaryzacja" %} {% endblock %}

{% block css %} 
	{{ block.super }}
	<link rel="stylesheet" href="{{ STATIC_URL }}lock/css/style.css" type="text/css" />
{% endblock %}

{% block horizontal_menu_items %} 

{% endblock %}

{% block breadcrumb %} 
	{{ block.super }}
	<a href="{% url apps.lock.views.index %}">{% trans "Inwentaryzacja" %}</a>
{% endblock %}
		
{% block content %}
	{% if form %}
		<div class="search_form">		
			<form action="" method="post">
				{% csrf_token %}
				{{ form.query.errors }}{{ form.query }}
				{% if request.user.get_profile.lockadmin %}
					{{ form.user }}
				{% endif %}
				<button class="button_2" type="submit">Szukaj</button>
			</form>
		</div>
	
		{% if items %}
			<table class="table_0 table_items">
				<thead>
					<tr>
						<td class="item">{% trans "Przedmiot" %}</td>
						<td class="serial_number">{% trans "Numer seryjny" %}</td>
						<td class="inventory_number">{% trans "Numer inwentarzowy" %}</td>
						<td class="type">{% trans "Typ" %}</td>
						<td class="room">{% trans "Pokój" %}</td>
						<td class="price">{% trans "Wartość" %}</td>
						<td class="user">{% trans "Powiązane osoby" %}</td>
						<td class="actions">{% trans "Actions" %}</td>
					</tr>
				</thead>
				<tbody>
					{% for item in items.object_list %}
					<tr>
						<td><a class="link_preview link_0" href="{% url apps.lock.views.show_item id_item=item.id %}">{{ item.name }}</a></td>
						<td>{{ item.serial_number }}</td>
						<td>{{ item.inventory_number }}</td>
						<td>{{ item.type }}</td>
						<td>{{ item.room }}</td>
						<td class="price">{{ item.price }} zł</td>
						<td>
							<ul class="square">
								{% for itemuser in item.itemuser_set.all %}
									<li>{{ itemuser.user }} ({{ itemuser.type }})</li>
								{% endfor %}
							</ul>
						</td>
						<td><a class="link_0 link_print" href="{% url apps.lock.views.print_receipt id_item=item.id %}" target="_blank">{% trans "Wydrukuj rewers" %}</a></td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
			
			{% paginator items %}
		{% else %}
			<ul class="infolist">
				<li>Lista przedmiotów do wyświetlenia jest pusta.</li>
			</ul>
		{% endif %}
	{% else %}
		<ul class="infolist">
			<li>Aplikacja przeznaczona wyłącznie dla pracowników Instytutu Informatyki.</li>
		</ul>
	{% endif %}
{% endblock %}

templates/lock/print_receipt.html
{% extends "base_0p.html" %}

{% load i18n %}

{% block css %}
	{{ block.super }}
	<link rel="stylesheet" href="{{ STATIC_URL }}syjon/css/print.css" type="text/css" />
	<style>
		p.no_margin {margin: 0 0 0 0;}
		p.no_margin_bottom {margin-bottom: 0;}
		p.small {margin: 0 0 0 0; font-size: 11px;}
		
		table td {border: 0px; font-size: 16px;}
   </style>
{% endblock %}

{% block body %}
	<div style="text-align: right; margin-bottom: 40px;">
		<p>Załącznik nr 3 do zarządzenia nr 10/98</p>
		<p>Lublin dn. {% now "d.m.Y" %}</p>
	</div>
	
	<div style="margin-bottom: 120px;">
		<p>Przekazujący:</p>
		<p class="no_margin_bottom"><b>{{ item.get_item_owner }}</b></p>
		<p class="small">(Imię i nazwisko osoby materialnie odpowiedzialnej)</p>
		<p class="no_margin_bottom"><b>{{ item.room.department.name }}</b></p>
		<p class="small">(Jednostka Organizacyjna UMCS)</p>
	</div>

	<h2 style="text-align: center; margin-bottom: 80px;">REWERS</h2>
	
	<div style="margin-bottom: 160px;">
		<p>Ninijszym przekazuję:</p>
		
		<p class="no_margin_bottom">Panu(i):</p>
		<p class="no_margin"><b>{{ item.get_item_user }}</b>;</p>
		<p class="no_margin_bottom">stanowisko służbowe:</p>
		<p class="no_margin"><b>{{ item.get_item_user.teacher.position }}</b>;</p>
		<p class="no_margin_bottom">określić rodzaj sprzętu:</p>
		<p class="no_margin"><b>{{ item }}, {{ item.inventory_number }}</b>;</p>
		<p style="text-align: justify">w&nbsp;celu wykonywania obowiązków wynikających ze stosunku pracy. Równocześnie informuję, iż Przyjmujący bierze pełną odpowiedzialność za jego użytkowanie, a&nbsp;w&nbsp;razie uszkodzenia lub zagubienia zobowiązuje się do naprawienia szkody w&nbsp;granicach rzeczywistej straty poniesionej przez pracodawcę.</p>
	</div>
	
	<table style="width: 100%; text-align: center;">
		<tr>
			<td>Przekazujący</td>
			<td>Przyjmujący</td>
		</tr>
	</table>
{% endblock %}

templates/lock/show_item.html
{% extends "lock/base.html" %}

{% load i18n %}

{% block page_title %} {% trans "Szczegóły przedmiotu" %} {% endblock %}

{% block breadcrumb %} 
	{{ block.super }}
	&raquo; <a href="{% url apps.lock.views.show_item id_item=item.id %}">{% trans "Szczegóły przedmiotu" %}</a>
{% endblock %}
		
{% block content %}
	<table class="table_0 table_item_details">
		<thead>
			<tr>
				<td colspan="2">{% trans "Szczegóły przedmiotu" %}</td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td class="label">{% trans "Nazwa" %}:</td>
				<td>{{ item.name }}</td>
			</tr>
			<tr>
				<td class="label">{% trans "Zdjęcie" %}:</td>
				<td class="image">
					{% if item.image %}
						<img src="{{MEDIA_URL}}{{ item.image }}"/>
					{% else %}
						&ndash;
					{% endif %}
				</td>
			</tr>
			<tr>
				<td class="label">{% trans "Numer seryjny" %}:</td>
				<td>{{ item.serial_number }}</td>
			</tr>
			<tr>
				<td class="label">{% trans "Numer inwentarzowy" %}:</td>
				<td>{{ item.inventory_number }}</td>
			</tr>
			<tr>
				<td class="label">{% trans "Typ" %}:</td>
				<td>{{ item.type }}</td>
			</tr>
			<tr>
				<td class="label">{% trans "Pokój" %}:</td>
				<td>{{ item.room }}</td>
			</tr>
			<tr>
				<td class="label">{% trans "Powiązane osoby" %}:</td>
				<td>
					<ul class="square">
						{% for itemuser in item.itemuser_set.all %}
							<li>{{ itemuser.user }} ({{ itemuser.type }})</li>
						{% endfor %}
					</ul>
				</td>
			</tr>
		</tbody>
	</table>
	<div class="spacer_10"></div>
	
	{% if item.property_set.all %}
		<table class="table_0">
			<thead>
				<tr>
					<td colspan="2">{% trans "Właściwości przedmiotu" %}</td>
				</tr>
			</thead>
			<tbody>
				{% for property in item.property_set.all %}
					<tr>
						<td class="label">{{ property.key }}:</td>
						<td> {{ property.value }}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
		<div class="spacer_10"></div>
	{% else %}
		<ul class="infolist">
			<li>{% trans "Żadne właściwości nie zostały przypisane do tego przedmiotu." %}</li>
		</ul>
	{% endif %}
	
	{% if item.related_items.all %}
		<table class="table_0">
			<thead>
				<tr>
					<td colspan="2">{% trans "Powiązane przedmioty" %}</td>
				</tr>
			</thead>
			<tbody>
				{% for related_item in item.related_items.all %}
					<tr>
						<td class="label">{{ related_item.type }}:</td>
						<td><a class="link_0 link_preview" target="_blank" href="{% url apps.lock.views.show_item id_item=related_item.id %}">{{ related_item }}</a></td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	{% else %}
		<ul class="infolist">
			<li>{% trans "Żadne inne przedmioty nie zostały powiązane z tym przedmiotem." %}</li>
		</ul>
	{% endif %}
{% endblock %}